# Generated by Django 6.0.2 on 2026-02-21 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('order_new', 'New Order'), ('order_status', 'Order Status'), ('low_stock', 'Low Stock'), ('payment', 'Payment'), ('review', 'Review'), ('system', 'System'), ('promo', 'Promo')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('channels', models.JSONField(default=list)),
                ('sent_via', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, max_length=2000, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('vendor_reply', models.TextField(blank=True, max_length=1000, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('flagged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread_id', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=2000)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
