# Generated by Django 6.0.2 on 2026-02-21 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('theme_id', models.CharField(default='default', max_length=50)),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business')], default='free', max_length=20)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('pending_balance', models.PositiveIntegerField(default=0)),
                ('commission_rate', models.PositiveIntegerField(default=500)),
                ('level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=2)),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
